package fr.baretto.ollamassist.chat.tools;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Parser for tool calls in the format: [CALL CreateFile('path', 'content')]
 * This format is sometimes generated by models that don't use native function calling.
 */
public class BracketCallParser implements ToolCallParser {

    // Pattern to match: [CALL ToolName('arg1', 'arg2', ...)]
    // Supports both single and double quotes
    private static final Pattern BRACKET_PATTERN = Pattern.compile(
            "\\[CALL\\s+([A-Za-z][A-Za-z0-9]*)\\s*\\((.*)\\)\\]",
            Pattern.DOTALL
    );

    @Override
    public Optional<DetectedToolCall> parse(String text) {
        if (text == null || text.isBlank()) {
            return Optional.empty();
        }

        Matcher matcher = BRACKET_PATTERN.matcher(text);
        if (!matcher.find()) {
            return Optional.empty();
        }

        String toolName = matcher.group(1);
        String argsText = matcher.group(2);

        // For CreateFile specifically, we expect 2 arguments: path and content
        if ("CreateFile".equals(toolName)) {
            Map<String, String> arguments = parseCreateFileArguments(argsText);
            if (!arguments.isEmpty()) {
                return Optional.of(DetectedToolCall.builder()
                        .toolName(toolName)
                        .arguments(arguments)
                        .originalText(matcher.group(0))
                        .detectedBy(getParserName())
                        .build());
            }
        }

        return Optional.empty();
    }

    private static final int MAX_ARGUMENTS = 10;

    /**
     * Parse CreateFile arguments from text like: 'path/to/file.java', 'content here'
     * Supports both single and double quotes.
     */
    private Map<String, String> parseCreateFileArguments(String argsText) {
        Map<String, String> arguments = new HashMap<>();

        // Match quoted strings (both single and double quotes)
        Pattern argPattern = Pattern.compile("['\"]([^'\"]*)['\"]");
        Matcher argMatcher = argPattern.matcher(argsText);

        int argIndex = 0;
        while (argMatcher.find() && argIndex < MAX_ARGUMENTS) {
            String value = argMatcher.group(1);
            if (argIndex == 0) {
                arguments.put("path", value);
            } else if (argIndex == 1) {
                arguments.put("content", value);
            }
            argIndex++;
        }

        // Must have both path and content
        if (arguments.containsKey("path") && arguments.containsKey("content")) {
            return arguments;
        }

        return new HashMap<>();
    }

    @Override
    public String getParserName() {
        return "BracketCallParser";
    }
}
